version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./staging.nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - events-api

  events-api:
    image: excelmec/events-api:staging
    container_name: events-api
    volumes:
      - ./Excel-Events-Backend/API/Keys/:/api/Keys/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - GOOGLE_CREDENTIAL_FILE=${GOOGLE_CREDENTIAL_FILE}
      - GOOGLE_CLOUD_STORAGE_BUCKET=${GOOGLE_CLOUD_STORAGE_BUCKET}
      - CLOUD_STORAGE_URL=${CLOUD_STORAGE_URL}
      - API_PREFIX=${API_PREFIX}
      - SECRET_KEY=${SECRET_KEY}
      - ACCOUNTS_HOST=${ACCOUNTS_HOST}
      - SERVICE_KEY=${SERVICE_KEY}
    ports:
      - '5000:5000'
